AskHuman Tool
kikoncuo/easy-assistants-server pull request #18
Opened 2024-06-10 15:43 UTC by lluiserena

2024-06-11 10:01 UTC, kikoncuo requested changes

2024-06-11 10:01 UTC, kikoncuo commented on tests/server.test.ts
> +test("Ask Human test", async () => {
Prueba que hace bien todos los pasos no solo el primero, por eso no hemos notado el error del paso 3

2024-06-11 10:31 UTC, lluiserena commented on tests/server.test.ts
> +test("Ask Human test", async () => {
No siempre planea hacer un chart, por lo que a veces puede dar error. Ahora he añadido que como mínimo compruebe el getData

2024-06-11 13:34 UTC, kikoncuo requested changes

2024-06-11 13:34 UTC, kikoncuo commented on src/models/Prompts.ts
> +#E3 would call the createChart tool with parameters ["#E2"] and describe the step as "Generate a chart to highlight the top 10 customers"
Missing step 1 as a parameter to step 3
would call the createChart tool with parameters [generate a chart with data #E2 in format #E1] and describe the step as "Generate a chart to highlight the top 10 customers"

2024-06-11 13:34 UTC, kikoncuo commented on tests/server.test.ts
> +test("Ask Human test", async () => {
ajusta el prompt del planner para que createChart mencione la palabra graph para que arregle esto

2024-06-12 16:31 UTC, kikoncuo approved these changes

2024-06-12 16:31 UTC, merged